# Generated by Django 5.1.1 on 2024-11-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, null=True)),
                ('nazwisko', models.CharField(max_length=100, null=True)),
                ('plec', models.CharField(choices=[('kobieta', 'Kobieta'), ('mezczyzna', 'Mężczyzna'), ('inne', 'Inne')], max_length=10)),
                ('stanowisko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal_app.stanowisko')),
            ],
        ),
    ]
