# Generated by Django 5.1.1 on 2025-01-27 22:11

# Generated by Django 5.1.1 on 2025-01-27 22:11

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('Journal_app', '0005_alter_osoba_data_dodania_delete_person_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='właściciel',
            field=models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]